-- CDP Audit Event Ordering DDL
--
-- Status: foundational fix discovered during challenge-adjudication (the
-- third vertical slice) verification. Scope: add a monotonic ordering
-- column to cdp_audit.event_log. No other table is touched.
--
-- Problem:
--   cdp_audit.event_log.created_at (from docker/postgres/init/01-init-cdp.sql)
--   defaults to now(), which in Postgres is transaction_timestamp() --
--   stable for the entire lifetime of one transaction, not per statement.
--   Every vertical slice in this codebase appends multiple audit events
--   inside a single service transaction (for example
--   create_decision_with_workflow appends decision.created,
--   workflow.started, and task.created together), so those events share
--   the exact same created_at value. created_at correctly answers "when
--   did this happen?"; it cannot answer "in what order did the audit log
--   record it?" once more than one event lands in the same transaction,
--   which is the normal case here, not an edge case.
--
--   A live manual verification during the adjudication slice confirmed
--   this is not theoretical: `ORDER BY created_at` returned same-
--   transaction events in a different order than they were inserted, and
--   in one case in fully reversed order, because Postgres does not
--   guarantee any particular result order for tied sort keys.
--
-- Fix:
--   Add event_sequence, a monotonically increasing identity column, as
--   the ordering key for cdp_audit.event_log. created_at is preserved
--   unchanged as the wall-clock timestamp column; it is no longer used
--   for ordering anywhere in this codebase. Query/test code should use
--   `ORDER BY event_sequence`, not `ORDER BY created_at`.
--
-- Backfill note:
--   Adding an identity column to a table that may already have rows
--   assigns event_sequence values in whatever order Postgres happens to
--   scan the existing rows, which is not guaranteed to match those rows'
--   true original insertion order (they had no ordering key either, only
--   the same transaction-stable created_at problem this migration fixes
--   going forward). This is a one-time limitation for any event_log rows
--   that predate this migration; all rows inserted after it get a
--   correctly ordered event_sequence.

CREATE SCHEMA IF NOT EXISTS cdp_audit;

ALTER TABLE cdp_audit.event_log
    ADD COLUMN IF NOT EXISTS event_sequence BIGINT GENERATED BY DEFAULT AS IDENTITY;

-- Postgres has no ADD CONSTRAINT IF NOT EXISTS; guard manually so this
-- migration stays rerun-safe.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'uq_event_log_event_sequence'
    ) THEN
        ALTER TABLE cdp_audit.event_log
            ADD CONSTRAINT uq_event_log_event_sequence UNIQUE (event_sequence);
    END IF;
END;
$$;

-- The UNIQUE constraint above already creates its own backing btree index
-- on event_sequence, which also serves ORDER BY event_sequence queries.
-- A second, separate index would be redundant.

COMMENT ON COLUMN cdp_audit.event_log.event_sequence IS
'Monotonic ordering key for the audit log. created_at remains the wall-clock timestamp and is transaction-stable (multiple events written in one transaction share the same created_at); order by event_sequence, not created_at.';
