"""Smoke tests for the 006 audit-event-ordering migration.

Two layers, following the pattern established elsewhere in this test suite:

1. static smoke tests that inspect the DDL text with no database dependency;
2. an optional Postgres integration smoke test, enabled only when
   CDP_TEST_DATABASE_URL is set, that proves 001 -> 003 -> 004 -> 005 -> 006
   apply cleanly, that 006 is idempotent, and -- the actual invariant this
   migration exists to fix -- that multiple events written inside a single
   transaction can share an identical created_at value while still being
   deterministically orderable by event_sequence.
"""

from __future__ import annotations

import os
import re
import unittest
from pathlib import Path
from typing import Any

import psycopg
from psycopg.types.json import Jsonb


REPO_ROOT = Path(__file__).resolve().parents[1]
DDL_001 = REPO_ROOT / "db" / "ddl" / "001-decision-registry-kernel.sql"
DDL_003 = REPO_ROOT / "db" / "ddl" / "003-nemawashi-workflow-rules.sql"
DDL_004 = REPO_ROOT / "db" / "ddl" / "004-decision-class-workflow-seed.sql"
DDL_005 = REPO_ROOT / "db" / "ddl" / "005-challenge-transition.sql"
DDL_006 = REPO_ROOT / "db" / "ddl" / "006-audit-event-ordering.sql"


def read_sql(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def strip_sql_comments(sql: str) -> str:
    """Drop `-- ...` line comments so text assertions ignore prose in comments."""
    return re.sub(r"--[^\n]*", "", sql)


class Migration006StaticTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.sql = read_sql(DDL_006)
        cls.executable_sql = strip_sql_comments(cls.sql)

    def test_migration_file_exists(self) -> None:
        self.assertTrue(DDL_006.exists(), "006 audit-event-ordering DDL should exist")

    def test_migration_is_additive_only(self) -> None:
        compact_sql = re.sub(r"\s+", " ", self.executable_sql.lower())
        for forbidden in ("drop table", "drop schema", "truncate", "delete from", "drop column"):
            self.assertNotIn(forbidden, compact_sql, f"006 should not contain: {forbidden}")

    def test_migration_adds_event_sequence_without_dropping_any_column(self) -> None:
        self.assertIn(
            "ADD COLUMN IF NOT EXISTS event_sequence BIGINT GENERATED BY DEFAULT AS IDENTITY",
            self.executable_sql,
        )
        self.assertNotIn("DROP COLUMN", self.executable_sql.upper())

    def test_migration_only_touches_event_log(self) -> None:
        self.assertIn("cdp_audit.event_log", self.executable_sql)
        for other_table in ("decision_registry", "workflow_instance", "workflow_task", "challenge_record"):
            self.assertNotIn(f"ALTER TABLE cdp_core.{other_table}", self.executable_sql)

    def test_unique_constraint_is_guarded_for_rerun_safety(self) -> None:
        """Postgres has no ADD CONSTRAINT IF NOT EXISTS, so this must be
        guarded some other way (e.g. a DO block checking pg_constraint)."""
        self.assertIn("uq_event_log_event_sequence", self.sql)
        self.assertIn("pg_constraint", self.executable_sql)


class Migration006PostgresSmokeTests(unittest.TestCase):
    """Optional Postgres execution smoke test.

    Set CDP_TEST_DATABASE_URL to enable. Applies 001, 003, 004, 005, then
    006 twice inside one transaction (rolled back at the end) to prove
    rerun-safety, and demonstrates the actual invariant this migration
    fixes: same-transaction events share created_at but are still
    deterministically ordered by event_sequence.
    """

    def test_apply_001_003_004_005_then_006_twice_is_idempotent(self) -> None:
        database_url = os.environ.get("CDP_TEST_DATABASE_URL")
        if not database_url:
            self.skipTest("set CDP_TEST_DATABASE_URL to run Postgres DDL smoke test")

        conn = self._connect(database_url)
        try:
            cursor = conn.cursor()
            cursor.execute(read_sql(DDL_001))
            cursor.execute(read_sql(DDL_003))
            cursor.execute(read_sql(DDL_004))
            cursor.execute(read_sql(DDL_005))
            cursor.execute(read_sql(DDL_006))
            # Rerun 006 alone to prove idempotency/rerun-safety.
            cursor.execute(read_sql(DDL_006))

            cursor.execute(
                """
                SELECT column_name FROM information_schema.columns
                WHERE table_schema = 'cdp_audit' AND table_name = 'event_log'
                  AND column_name = 'event_sequence'
                """
            )
            self.assertIsNotNone(cursor.fetchone(), "missing cdp_audit.event_log.event_sequence")

            cursor.execute(
                """
                SELECT 1 FROM pg_constraint WHERE conname = 'uq_event_log_event_sequence'
                """
            )
            self.assertIsNotNone(cursor.fetchone(), "missing uq_event_log_event_sequence")
        finally:
            conn.rollback()
            conn.close()

    def test_same_transaction_events_share_created_at_but_order_by_event_sequence(self) -> None:
        """This is the actual invariant 006 exists to fix: prove that events
        written inside one transaction can have an identical created_at
        (because now() is transaction_timestamp() in Postgres) while
        event_sequence still gives a deterministic, monotonic order."""
        database_url = os.environ.get("CDP_TEST_DATABASE_URL")
        if not database_url:
            self.skipTest("set CDP_TEST_DATABASE_URL to run Postgres DDL smoke test")

        conn = self._connect(database_url)
        try:
            cursor = conn.cursor()
            cursor.execute(read_sql(DDL_001))
            cursor.execute(read_sql(DDL_003))
            cursor.execute(read_sql(DDL_004))
            cursor.execute(read_sql(DDL_005))
            cursor.execute(read_sql(DDL_006))

            aggregate_id = "audit-ordering-smoke-test"
            expected_order = ["alpha", "beta", "gamma"]
            for event_type in expected_order:
                cursor.execute(
                    """
                    INSERT INTO cdp_audit.event_log (event_type, aggregate_type, aggregate_id, payload)
                    VALUES (%s, 'smoke_test', %s, %s)
                    """,
                    (event_type, aggregate_id, Jsonb({})),
                )

            cursor.execute(
                "SELECT DISTINCT created_at FROM cdp_audit.event_log WHERE aggregate_id = %s",
                (aggregate_id,),
            )
            distinct_timestamps = cursor.fetchall()
            self.assertEqual(
                len(distinct_timestamps),
                1,
                "all three events in this transaction should share one created_at value "
                "(now() is transaction-stable in Postgres) -- this is exactly the "
                "invariant event_sequence exists to fix",
            )

            cursor.execute(
                "SELECT event_type FROM cdp_audit.event_log "
                "WHERE aggregate_id = %s ORDER BY event_sequence",
                (aggregate_id,),
            )
            actual_order = [row[0] for row in cursor.fetchall()]
            self.assertEqual(actual_order, expected_order)
        finally:
            conn.rollback()
            conn.close()

    def test_backfills_event_sequence_for_pre_existing_rows_safely(self) -> None:
        """cdp_audit.event_log is a foundational, already-used table -- this
        proves 006 is safe to run against one that already has rows, not
        just against a freshly-created empty table.

        Applies schema through 005 (no 006), inserts pre-existing event_log
        rows in one transaction, then applies 006 and confirms: every
        pre-existing row gets a non-null, unique event_sequence; ordering
        by event_sequence is deterministic; and rows inserted after 006
        continue the same sequence without colliding.
        """
        database_url = os.environ.get("CDP_TEST_DATABASE_URL")
        if not database_url:
            self.skipTest("set CDP_TEST_DATABASE_URL to run Postgres DDL smoke test")

        conn = self._connect(database_url)
        try:
            cursor = conn.cursor()
            cursor.execute(read_sql(DDL_001))
            cursor.execute(read_sql(DDL_003))
            cursor.execute(read_sql(DDL_004))
            cursor.execute(read_sql(DDL_005))
            # Deliberately not applying 006 yet.

            aggregate_id = "audit-ordering-pre-existing-rows-smoke-test"
            pre_existing_types = ["pre.one", "pre.two", "pre.three"]
            for event_type in pre_existing_types:
                cursor.execute(
                    """
                    INSERT INTO cdp_audit.event_log (event_type, aggregate_type, aggregate_id, payload)
                    VALUES (%s, 'smoke_test', %s, %s)
                    """,
                    (event_type, aggregate_id, Jsonb({})),
                )

            cursor.execute(
                "SELECT count(*) FROM cdp_audit.event_log WHERE aggregate_id = %s",
                (aggregate_id,),
            )
            self.assertEqual(cursor.fetchone()[0], len(pre_existing_types))

            # Now apply the migration against a table that already has rows.
            cursor.execute(read_sql(DDL_006))

            cursor.execute(
                "SELECT event_type, event_sequence FROM cdp_audit.event_log "
                "WHERE aggregate_id = %s ORDER BY event_sequence",
                (aggregate_id,),
            )
            rows = cursor.fetchall()
            self.assertEqual(len(rows), len(pre_existing_types))

            sequences = [row[1] for row in rows]
            for sequence in sequences:
                self.assertIsNotNone(sequence, "pre-existing row is missing event_sequence")
            self.assertEqual(
                len(sequences), len(set(sequences)), "event_sequence values must be unique"
            )
            self.assertEqual(
                sequences,
                sorted(sequences),
                "event_sequence must be monotonically orderable for pre-existing rows",
            )

            # Ordering by event_sequence must be deterministic across repeated queries.
            cursor.execute(
                "SELECT event_type FROM cdp_audit.event_log "
                "WHERE aggregate_id = %s ORDER BY event_sequence",
                (aggregate_id,),
            )
            first_read_order = [row[0] for row in cursor.fetchall()]
            cursor.execute(
                "SELECT event_type FROM cdp_audit.event_log "
                "WHERE aggregate_id = %s ORDER BY event_sequence",
                (aggregate_id,),
            )
            second_read_order = [row[0] for row in cursor.fetchall()]
            self.assertEqual(first_read_order, second_read_order)

            # A row inserted after 006 must also receive an event_sequence,
            # continuing the same monotonic sequence.
            cursor.execute(
                """
                INSERT INTO cdp_audit.event_log (event_type, aggregate_type, aggregate_id, payload)
                VALUES ('post.migration', 'smoke_test', %s, %s)
                RETURNING event_sequence
                """,
                (aggregate_id, Jsonb({})),
            )
            new_sequence = cursor.fetchone()[0]
            self.assertIsNotNone(new_sequence)
            self.assertGreater(new_sequence, max(sequences))
        finally:
            conn.rollback()
            conn.close()

    @staticmethod
    def _connect(database_url: str) -> Any:
        return psycopg.connect(database_url)


if __name__ == "__main__":
    unittest.main()
